### ISSUE TITLE
Exception during teleportation

### ISSUE THREAD

**Issue by Yamakaja** [Yamakaja/rpgpets#5]
https://sentry.io/yamakaja/rpgpets/issues/317230980/

```
NullPointerException: None
    at me.yamakaja.rpgpets.api.entity.PetManager.onTeleport(PetManager.java:348)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
...
(27 additional frame(s) were not displayed)

EventException: None
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:482)
...
(22 additional frame(s) were not displayed)
```

**Comment by Yamakaja** [comment]
Relevant line: https://github.com/Yamakaja/rpgpets/blob/01bceb67e9f9a8eee5ac3aa49b304df0979a47ba/api/src/main/java/me/yamakaja/rpgpets/api/entity/PetManager.java#L348-L348

The teleportation target might have been null?
