### ISSUE TITLE
v1.1.16 Error 

### ISSUE THREAD

**Issue by aoov** [Yamakaja/rpgpets#7]
Been getting this on start up and preventing the plugin from working 

` Error occurred while enabling RPGPets v1.1.16 (Is it up to date?)
java.lang.NullPointerException: null
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at me.yamakaja.rpgpets.api.config.ConfigManager.injectConfigs(ConfigManager.java:53) ~[?:?]
	at me.yamakaja.rpgpets.plugin.RPGPetsImpl.onEnable(RPGPetsImpl.java:56) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by Yamakaja** [comment]
You probably missed the warning in the update entry https://www.spigotmc.org/resources/rpgpets.42653/update?update=210150

**Comment by aoov** [comment]
Ahh. Sorry about that :p

**Comment by Yamakaja** [comment]
I assume the problem has been resolved?
